# Generated by Django 2.2 on 2019-06-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_ticker_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='ticker',
            field=models.CharField(max_length=10),
        ),
    ]
