# Generated by Django 2.2 on 2019-06-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20190614_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='ticker',
            field=models.TextField(max_length=10),
        ),
    ]
