# Generated by Django 2.2 on 2019-06-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20190614_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='interval',
            field=models.CharField(choices=[(1, '1'), (5, '5'), (15, '15'), (30, '30'), (60, '60')], default=30, max_length=2),
        ),
    ]
