# Generated by Django 2.2 on 2019-06-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_ticker_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='time_series',
            field=models.CharField(choices=[('INTRADAY', 'Intraday'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='MONTHLY', max_length=20),
        ),
    ]
