# Generated by Django 2.2 on 2019-06-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_ticker_time_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='interval',
            field=models.IntegerField(choices=[(1, '1'), (5, '5'), (15, '15'), (30, '30'), (60, '60')], default=30),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='time_series',
            field=models.IntegerField(choices=[('INTRADAY', 'Intraday'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='MONTHLY'),
        ),
    ]
