# Generated by Django 2.2 on 2019-06-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_auto_20190625_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='time_series',
            field=models.CharField(choices=[('INTRADAY', 'Intraday'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='MONTHLY', max_length=20),
        ),
    ]
