# Generated by Django 2.2 on 2019-06-25 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_auto_20190625_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_price', models.IntegerField()),
                ('high_price', models.IntegerField()),
                ('low_price', models.IntegerField()),
                ('close_price', models.IntegerField()),
                ('volume_price', models.IntegerField()),
                ('amount_bought', models.IntegerField()),
                ('amount_spent', models.IntegerField()),
                ('time_bought', models.IntegerField(blank=True, null=True)),
                ('time_sold', models.IntegerField(blank=True, null=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.Ticker')),
            ],
        ),
    ]
