# Generated by Django 2.2 on 2019-06-26 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_auto_20190626_1946'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TickerPrices',
            new_name='TickerPrice',
        ),
    ]
