# Generated by Django 2.2 on 2019-06-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_auto_20190626_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='time_series',
            field=models.CharField(blank=True, choices=[('INTRADAY', 'Intraday'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='MONTHLY', max_length=20, null=True),
        ),
    ]
