# Generated by Django 2.2 on 2019-06-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_auto_20190626_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='interval',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (5, '5'), (15, '15'), (30, '30'), (60, '60')], default=30, null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='time_series',
            field=models.CharField(choices=[('INTRADAY', 'Intraday'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='MONTHLY', max_length=20),
        ),
    ]
