# Generated by Django 2.2 on 2019-06-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_auto_20190626_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='time_series',
            field=models.CharField(choices=[('Intraday', 'Intraday'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='Monthly', max_length=20),
        ),
    ]
