# Generated by Django 2.2 on 2019-06-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0019_auto_20190626_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='interval',
            field=models.IntegerField(choices=[(1, '1'), (5, '5'), (15, '15'), (30, '30'), (60, '60')], default=30),
        ),
    ]
