# Generated by Django 2.2 on 2019-06-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0020_auto_20190626_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='interval',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (5, '5'), (15, '15'), (30, '30'), (60, '60')], null=True),
        ),
    ]
