# Generated by Django 2.2 on 2019-06-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0021_auto_20190626_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='time_series',
            field=models.CharField(choices=[('Intraday', 'Intraday'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], max_length=20),
        ),
    ]
