# Generated by Django 2.2 on 2019-06-28 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0022_auto_20190626_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickerprice',
            name='ticker',
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.DeleteModel(
            name='TickerPrice',
        ),
    ]
